### ISSUE TITLE
Fix the Ae'gura museum/library doors

### ISSUE THREAD

**Issue by dpogue** [H-uru/moul-assets#129]
These have always been buggy in multiplayer. In the UU days, I vaguely recall ycikamookow finding a way to fix them, but Cyan eventually gave up trying to fix them in MOUL and just disabled them entirely.

I suspect we can probably collectively brainstorm a way to make them work as intended, even in multiplayer.

**Comment by DamnBriggsy** [comment]
I'm not sure if the door in Ahnonay Cathedral is set up the same way as these two doors, but does have buggy behavior when multiple people try to walk through it.

**Comment by DoobesURU** [comment]
> > The door in AhnyCathedral is not multiplayer aware.
> 
> ... can it be, though? Considering that MOUL-type shards require bringing a friend through there. (sorry, spoilers, lol? 🤷)

Should be easy to do. Just need to tie it to a new SDL state and presto.

**Comment by Hazado** [comment]
> The door in AhnyCathedral is not multiplayer aware.

Doesnt even use python file mods, just a responder to open them

**Comment by patmauro** [comment]
As with https://github.com/H-uru/moul-assets/issues/33, I believe this should now be resolved by https://github.com/H-uru/moul-assets/pull/242 and https://github.com/H-uru/Plasma/pull/1462 and should be able to be closed.
