### ISSUE TITLE
Teledahn has improper camera flip when descending ladder

### ISSUE THREAD

**Issue by ZarothYe** [H-uru/moul-assets#165]
On current TL. Haven't checked Gehn, but Minkata/MOULa do not do this -- they have a (rail?) camera that follows the avvie downwards in the well until the final stationary camera point seen at the end of the video.

https://user-images.githubusercontent.com/94947971/177074237-86a562d1-6f08-4038-a7b8-79ee44ca1403.mp4

**Comment by Hoikas** [comment]
This issue pertains to a problem in H-uru/Plasma#1127 that has been corrected.
