### ISSUE TITLE
Phil's Relto - rain effect starts late

### ISSUE THREAD

**Issue by patmauro** [H-uru/moul-assets#188]
This has been discussed previously, but just to officially log this - in Phil's Relto, the rain effect begins late, about 30 seconds after linking into the age rather than right away.

It is possible something may have been incorrectly ported here from Rainy Cleft, as this 30ish-second interval appears to match the same 30ish-second pause that occurs before the rain effect begins in that age for dramatic effect. However in that case the pause is clearly intentional, and there are matching changes in ambient sounds, water ripple effects, etc to time with this, whereas in Phil's Relto this appears to be a clear mistake - we hear rain, but do not see it.

**Comment by dpogue** [comment]
Does this happen with the rainy page in (normal) Relto too?

**Comment by patmauro** [comment]
> Does this happen with the rainy page in (normal) Relto too?

No; behaves correctly in normal!Relto as far as I can tell.

**Comment by Hazado** [comment]
The hsBezScalarKey in the "RainParty_rain_anim_0" ATC Anim start with a value of 0 which means no particles.
Just need to change the value to 600.
I can submit a fix for this soon, if no one else gets around to it.
