### ISSUE TITLE
Corrupted Files?

### ISSUE THREAD

**Issue by MaxwellEdison** [H-uru/moul-assets#222]
Hey, I've tried to download the project, however it appears as though all of the file content has been replaced with text.  For an example, attempting to open the AhnonayCathedral.blend in blender results in an unsupported file error.  If I open it in notepad++, it gives me:

version https://git-lfs.github.com/spec/v1
oid sha256:fcdbfab5f89942c899eaf8b7f1eb01a3a2ab57bec6f06daab413d5d8c553d451
size 23180444

All of the other files appear to be similar. 

Is there something I need to do in order to be able to download the actual files?  Are these files hosted elsewhere?

**Comment by bertvandepoel** [comment]
Hey Maxwell. For moul-assets, the H'uru project is using LFS (Git Large File System) to store the actual files, as they are too large for GitHub. I suggest you use "git lfs clone" instead of "git clone". That ought to help. Let us know if that fixes things! :)

**Comment by MaxwellEdison** [comment]
Alright, it looks like it's downloading the files now.  If I may make a suggestion, you might want to mention that you're using Git LFS and a quick "download git lfs here and run this command" tutorial in the readme for people who aren't familiar with github/git lfs.

**Comment by Deledrius** [comment]
@MaxwellEdison Good suggestion.  We have instructions for contributing but not the initial clone.  Whoops!  Thanks for pointing that out.
