### ISSUE TITLE
Spyroom: Inconsistent sfx when linking to Phil's Relto

### ISSUE THREAD

**Issue by patmauro** [H-uru/moul-assets#226]
The linking sound consistently does not trigger when using the book to Phil's Relto from Spyroom. While the link sound can famously be a little finnicky, that isn't the case here; this appears to be _consistent_ behavior specific to this link. Not a huge issue, but should ideally be looked into.

I've been able to confirm this on MOUL, Gehn, and Minkata on both client versions.

Demonstration: https://youtu.be/RVnAIcv8mSM

**Comment by Hoikas** [comment]
I cannot reproduce this issue.

**Comment by patmauro** [comment]
For clarification, this is what I'm referring to - I've been able to confirm this on MOUL, Gehn, and Minkata on both client versions. https://youtu.be/RVnAIcv8mSM

**Comment by patmauro** [comment]
I am closing this since nobody has been able to reproduce (and I haven't seen this crop up recently either) but might be worth taking a closer look at link sound triggers at some point and what can cause them to not fire properly - they can sometimes be pretty weird in contexts beyond just the Spyroom.
