### ISSUE TITLE
Keep female avatar nails/gloves/bracelet color for the different Hand Options

### ISSUE THREAD

**Issue by TheScarFr** [H-uru/moul-assets#254]
For example, if a female avatar have selected the "Fingerless Gloves" Hand Option with the red color for the nails and the black color for the gloves:
If the player now select the "Hand" Hand Option, the nails become black.
If the player select the red color for the nails and now select the "Fingerless Gloves" Hand Option, both the nails and the gloves are red.

The new version of the "GlobalClothing_District_Female.prp" file that is in this archive, allow the female avatar to keep the nails/gloves colors while the player is selecting a different Hand Option in the wardrobe.
Note: The archive also contains a "changes.txt" file that lists all the changes I did.

Edit; Archive removed.

**Comment by Hoikas** [comment]
These changes need to be made to the clothing max files and exported for us to be able to accept them. Otherwise, the changes will be overwritten the next time someone makes changes to the female clothing max files.

**Comment by TheScarFr** [comment]
I grouped the new version of the "`GlobalClothing_District_Female.prp`" file with some other files, in this new archive.
[TrigonBracelet_-_24-04-29.zip](https://github.com/H-uru/moul-assets/files/15155527/TrigonBracelet_-_24-04-29.zip)

**Comment by EhrenCG** [comment]
> These changes need to be made to the clothing max files and exported for us to be able to accept them. Otherwise, the changes will be overwritten the next time someone makes changes to the female clothing max files.

Do "GlobalClothing_District_FemaleFan02.prp" and "GlobalClothing_District_MaleFan02.prp" have Max files?  Or are manual PRC edits acceptable due to a lack of a Max source from which to export?

**Comment by TheScarFr** [comment]
How to use the "CreateClothingPRP.py" file?

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_03.zip](https://github.com/H-uru/moul-assets/files/15201438/TrigonBracelet_24_05_03.zip)

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_03.zip](https://github.com/H-uru/moul-assets/files/15201709/TrigonBracelet_24_05_03.zip)

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_10.zip](https://github.com/H-uru/moul-assets/files/15269221/TrigonBracelet_24_05_10.zip)

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_12.zip](https://github.com/H-uru/moul-assets/files/15284745/TrigonBracelet_24_05_12.zip)

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_12.zip](https://github.com/H-uru/moul-assets/files/15286300/TrigonBracelet_24_05_12.zip)

**Comment by TheScarFr** [comment]
New archive: [TrigonBracelet_24_05_17.zip](https://github.com/H-uru/moul-assets/files/15351313/TrigonBracelet_24_05_17.zip)

**Comment by TheScarFr** [comment]
Archive updated: [TrigonBracelet_24_05_17.zip](https://github.com/H-uru/moul-assets/files/15355207/TrigonBracelet_24_05_17.zip)

**Comment by TheScarFr** [comment]
Archive updated: [TrigonBracelet_24_05_21.zip](https://github.com/H-uru/moul-assets/files/15391537/TrigonBracelet_24_05_21.zip)

**Comment by TheScarFr** [comment]
Archive updated: [TheScar.fr-FemaleHandsOptionsColorsFix-24_09_04.zip](https://github.com/user-attachments/files/16871644/TheScar.fr-FemaleHandsOptionsColorsFix-24_09_04.zip)

**Comment by TheScarFr** [comment]
I updated the "bas.avatar.female.max" file (3DS Max 2022) and exported it to get the new "GlobalClothing_District_Female.prp" file. [TheScar.fr-FemaleHandsOptionsColorsFix-24_10_09.zip](https://github.com/user-attachments/files/17318509/TheScar.fr-FemaleHandsOptionsColorsFix-24_10_09.zip)

**Comment by TheScarFr** [comment]
Fix: #266
