### ISSUE TITLE
Fix the city doors (library & museum)

### ISSUE THREAD

**Issue by dpogue** [H-uru/moul-assets#33]
These have always been a synchronization problem, but I seem to recall a certain mookow getting them working properly for UU.

Would be nice to reinstate those doors and have them working as intended.

**Comment by Deledrius** [comment]
I would love to see these finally fixed!

**Comment by patmauro** [comment]
This has been resolved by https://github.com/H-uru/moul-assets/pull/242 and https://github.com/H-uru/Plasma/pull/1462 and can now be closed! 😃
